/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Fernanda and Karla
 */
public class FrmStart extends javax.swing.JFrame {

    /**
     * Creates new form FrmStart
     */
    public FrmStart() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnInstructions = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSettings = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        WallpaperLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PLAY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 130, 70));

        btnPlay.setBackground(new java.awt.Color(214, 151, 21));
        btnPlay.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-10-iloveimg-resized.png"))); // NOI18N
        btnPlay.setText("Play");
        btnPlay.setBorder(null);
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-14-iloveimg-resized.png"))); // NOI18N
        btnPlay.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-14-iloveimg-resized.png"))); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 130, 50));

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INSTRUCTIONS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 160, 90));

        btnInstructions.setBackground(new java.awt.Color(214, 151, 21));
        btnInstructions.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        btnInstructions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-10-iloveimg-resized.png"))); // NOI18N
        btnInstructions.setText("INSTRUCTIONS");
        btnInstructions.setBorderPainted(false);
        btnInstructions.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-14-iloveimg-resized.png"))); // NOI18N
        btnInstructions.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-14-iloveimg-resized.png"))); // NOI18N
        btnInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstructionsActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 160, 50));

        jLabel4.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SETTINGS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 120, 70));

        btnSettings.setBackground(new java.awt.Color(214, 151, 21));
        btnSettings.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-10-iloveimg-resized.png"))); // NOI18N
        btnSettings.setText("SETTINGS");
        btnSettings.setBorderPainted(false);
        btnSettings.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-14-iloveimg-resized.png"))); // NOI18N
        btnSettings.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-14-iloveimg-resized.png"))); // NOI18N
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 130, 50));

        jLabel5.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EXIT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 120, 70));

        btnExit.setBackground(new java.awt.Color(214, 151, 21));
        btnExit.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-10-iloveimg-resized.png"))); // NOI18N
        btnExit.setText("EXIT");
        btnExit.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 102, 0), null));
        btnExit.setBorderPainted(false);
        btnExit.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-14-iloveimg-resized.png"))); // NOI18N
        btnExit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fall-But-14-iloveimg-resized.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 90, 50));

        WallpaperLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Fondo5_bg.jpg"))); // NOI18N
        getContentPane().add(WallpaperLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/one.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 280, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        //Open the game window
        FrmGame game = new FrmGame();
        game.setLocationRelativeTo(null);
        game.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstructionsActionPerformed
        //Open the instructions window
        FrmInstructionsNew instructions = new FrmInstructionsNew();
        instructions.setLocationRelativeTo(null);
        instructions.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInstructionsActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        //Opens the settings window
        FrmSettingsNew settings = new FrmSettingsNew();
        settings.setLocationRelativeTo(null);
        settings.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //To exit the game
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WallpaperLabel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInstructions;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
